### ISSUE TITLE
feature: adding some tags to assembly/config/etc/ used by graphicpacks and mods

### ISSUE THREAD

**Issue by bseiller** [Caldfir/RCFC2#2]
I'm using your library to merge a revised version of the raws containing bugfixes (https://github.com/nc-z/df-revised) with the raws of the graphic packs like Phoebus being provided by PeridexisErrant's Starter Pack.
While playing around with the merging there were warnings logged that some tags are unkown.
I added them locally myself, but since they are used by more then one graphic pack it would be really handy if they were already included in the base version of your library.
Following the tags

in PLANT.txt
DEAD_PICKED_TILE
DEAD_SAPLING_TILE
SAPLING_TILE

in REACTION.txt (used by df-revised)
DESCRIPTION

Cheers!
PS: You library really saved me time!

**Comment by Caldfir** [comment]
Will do.  It is hard tracking down all the possible tags since there isn't consistent documentation really describing them fully, so people finding+reporting stuff really helps.

**Comment by bseiller** [comment]
Thank you - I'll keep reporting missings tags at least till I've found a new graphic pack I feel comfortable with.
